export const assessmentModes = [
  {
    title: "新案前期評估",
    summary: "從基地條件開始建立完整試算，逐步帶入容積、坪效、成本、分配、銷售、現金流與銀行報告。",
  },
  {
    title: "進行中案件承接評估",
    summary: "針對已整合到一半、已有分配條件或送件進度的案件，檢核三策是否適合介入、協助或承接。",
  },
  {
    title: "既有條件反推評估",
    summary: "輸入既有條件，反推坪效、成本、分配、銷售與資金需求，判斷目前條件是否仍具可行性。",
  },
];

export const assessmentFlows = [
  {
    title: "新案前期評估",
    steps: ["基地資料", "容積來源", "坪效明細", "成本", "分配", "銷售", "現金流", "銀行報告"],
  },
  {
    title: "進行中案件反推",
    steps: ["既有條件", "反推坪效 / 成本 / 分配 / 銷售", "判斷可行性", "承接風險", "調整建議", "銀行或地主說明報告"],
  },
];

export const roleVisibilityRules = {
  roles: [
    {
      key: "admin",
      label: "三策管理員",
      description: "可查看管理端模組、全系統預設參數、授權管理、安全防護、承接評估與銀行融資報告。",
    },
    {
      key: "user",
      label: "一般使用者",
      description: "只能查看案件評估流程與授權方案開放的模組，不顯示三策管理端功能。",
    },
  ],
  moduleRules: [
    {
      target: "授權管理",
      rule: "三策管理端功能，僅 admin 可見，一般使用者不顯示。",
    },
    {
      target: "安全防護",
      rule: "三策管理端功能，僅 admin 可見，一般使用者不顯示。",
    },
    {
      target: "承接評估",
      rule: "依授權方案決定是否顯示，未授權則不出現在 sidebar 底部入口。",
    },
    {
      target: "銀行融資報告",
      rule: "依授權方案決定是否顯示，未授權則不出現在一般模組導覽。",
    },
  ],
  parameterRules: [
    {
      target: "案件個別參數",
      rule: "一般使用者可看可調整，僅影響目前案件。",
    },
    {
      target: "全系統預設參數",
      rule: "僅 admin 可看可調整，一般使用者不顯示。",
    },
  ],
  backendRequirements: [
    "正式上線時，後端必須檢查角色與授權方案",
    "不可只靠前端隱藏管理端模組",
    "API 必須檢查是否可使用承接評估",
    "API 必須檢查是否可使用銀行融資報告",
    "參數儲存 API 必須區分案件個別參數與全系統預設參數",
  ],
};

export const developmentPaths = [
  {
    title: "購地自建",
    summary: "重點是土地取得成本、總開發成本、全部可售坪數與投資效益。",
    tags: ["土地取得", "全案自建", "投資效益"],
  },
  {
    title: "一般合建",
    summary: "重點是坪換坪、地主分回、開發方可銷售坪數。",
    tags: ["坪換坪", "地主分回", "找補條件"],
  },
  {
    title: "危老重建",
    summary: "重點是危老獎勵、容積移轉、合建條件與地主分回。",
    tags: ["危老獎勵", "容積移轉", "合建條件"],
  },
  {
    title: "都市更新",
    summary: "重點是都更獎勵、中央獎勵、地方獎勵、容積移轉、協議合建或權利變換。",
    tags: ["都更獎勵", "權利變換", "協議合建"],
    children: [
      {
        title: "協議合建",
        items: ["坪換坪", "比例分配", "自訂分配條件"],
      },
      {
        title: "權利變換",
        items: ["事業計畫與權利變換計畫併送", "事業計畫與權利變換計畫分送"],
      },
    ],
  },
  {
    title: "自主更新",
    summary:
      "重點是地主自辦、更新會或社區主導、專業服務費、地主自負額、融資需求與分配結果。",
    tags: ["地主自辦", "更新會", "融資需求"],
  },
];

export const evaluationModules = [
  {
    id: "case-management",
    title: "案件管理",
    eyebrow: "CASE",
    modeOptions: assessmentModes,
    description: "建立案件列表、狀態追蹤與版本管理，作為所有評估資料的入口。",
    sections: [
      {
        title: "案件列表骨架",
        fields: ["案件編號", "案件名稱", "開發路徑", "案件狀態", "負責顧問", "最後更新", "版本備註"],
      },
      {
        title: "案件狀態",
        options: ["前期評估", "條件確認", "地主整合", "審議準備", "銀行評估", "暫停追蹤"],
      },
    ],
  },
  {
    id: "takeover-evaluation",
    title: "進行中案件承接評估",
    eyebrow: "TAKEOVER",
    shortTitle: "承接評估",
    description:
      "既有條件反推評估會輸入目前已存在的分配條件、成本假設、銷售假設、整合與送件狀態，反推案件是否仍具可行性，以及三策是否有介入、協助或承接空間。",
    type: "takeover",
    modeOptions: assessmentModes,
    flows: assessmentFlows,
    references: [
      "開發路徑選擇",
      "容積來源與獎勵試算",
      "坪效明細計算",
      "成本與共同負擔",
      "實施方式與權利分配",
      "銷售價格情境",
      "現金流與資金需求",
      "銀行融資報告",
    ],
    sections: [
      {
        title: "目前案件狀態",
        fields: [
          "目前案件階段",
          "目前開發路徑",
          "目前實施方式",
          "是否已有整合團隊",
          "是否已有建築師",
          "是否已有估價師",
          "是否已有都更規劃團隊",
          "是否已有銀行接洽",
          "目前主要問題",
          "承接來源備註",
        ],
      },
      {
        title: "目前整合狀態",
        fields: [
          "地主總人數",
          "已接觸人數",
          "已同意人數",
          "已簽約人數",
          "反對或觀望人數",
          "目前同意比例",
          "是否達門檻",
          "主要反對原因",
          "整合風險備註",
        ],
      },
      {
        title: "既有分配條件",
        options: ["坪換坪", "比例分配", "權利變換預估分配", "其他"],
        fields: [
          "已談分配模式",
          "每坪土地換建坪",
          "地主分回比例",
          "實施者分回比例",
          "預估共同負擔比例",
          "已承諾地主坪數",
          "已承諾車位數",
          "找補條件",
          "條件是否已書面化",
          "分配條件備註",
        ],
      },
      {
        title: "既有容積與坪效假設",
        fields: [
          "目前假設基準容積率",
          "目前假設都更獎勵",
          "目前假設危老獎勵",
          "目前假設容積移轉",
          "目前假設總獎勵值",
          "目前假設銷售係數",
          "目前假設可售坪數",
          "目前假設總樓地板面積",
          "是否已有建築師量體",
          "坪效假設備註",
        ],
      },
      {
        title: "既有成本假設",
        fields: [
          "目前估算總成本",
          "營建成本假設",
          "容積取得成本假設",
          "標章與保證金假設",
          "規劃設計與專業費假設",
          "融資利息假設",
          "銷售管理費假設",
          "不可預見費假設",
          "成本是否有明細",
          "成本風險備註",
        ],
      },
      {
        title: "既有銷售與收益假設",
        fields: [
          "目前假設銷售單價",
          "銷售單價區間",
          "目前假設總銷售收入",
          "開發方可銷售坪數",
          "預估利潤",
          "預估利潤率",
          "預估損益平衡單價",
          "銷售假設備註",
        ],
      },
      {
        title: "目前行政與送件狀態",
        fields: [
          "是否已提事業概要",
          "是否已送事業計畫",
          "是否已送權利變換計畫",
          "併送或分送",
          "是否已進審議",
          "是否已有審議意見",
          "是否已有都更會或更新會",
          "是否已核定",
          "是否有法規或程序卡點",
          "行政進度備註",
        ],
      },
    ],
    riskChecklist: [
      "目前別人談出來的條件合不合理？",
      "照目前分配條件，開發方還剩多少可銷售坪數？",
      "目前承諾地主的條件會不會太高？",
      "目前成本是否低估？",
      "目前銷售價格是否過度樂觀？",
      "共同負擔比例是否合理？",
      "目前整合進度與送件進度是否足以承接？",
      "三策是否有介入、協助或承接空間？",
      "這個案子的風險缺口在哪裡？",
    ],
    outputSections: [
      "分配條件合理性",
      "成本假設合理性",
      "銷售假設合理性",
      "共同負擔比例合理性",
      "開發方可分回坪數是否足夠",
      "損益平衡風險",
      "現金流風險",
      "融資可行性",
      "承接可行性",
      "主要風險缺口",
      "建議調整方向",
    ],
  },
  {
    id: "base-info",
    title: "基地基本資料",
    eyebrow: "SITE",
    description: "先建立基地條件資料，後續容積、成本、分配與融資報告都會引用這一層。",
    sections: [
      {
        title: "基本欄位",
        fields: [
          "案件名稱",
          "基地位置",
          "縣市",
          "行政區",
          "地段",
          "地號",
          "土地面積",
          "使用分區",
          "建蔽率",
          "基準容積率",
          "公告現值",
          "公告地價",
          "臨路條件",
          "基地形狀",
          "法規限制",
          "備註",
        ],
      },
    ],
  },
  {
    id: "development-path",
    title: "開發路徑選擇",
    eyebrow: "PATH",
    description: "先依案件性質選擇試算路徑，再帶出對應的分配、成本與報告欄位。",
    type: "paths",
  },
  {
    id: "capacity",
    title: "容積來源與獎勵試算",
    eyebrow: "FAR",
    description: "先建立容積來源、獎勵與容積移轉欄位骨架，正式公式後續再接入。",
    sections: [
      { title: "容積來源", fields: ["基準容積", "中央獎勵", "地方獎勵", "危老獎勵", "其他容積來源", "容積合計摘要"] },
      {
        title: "容積移轉 / 新北市平點評點預留",
        fields: [
          "適用縣市",
          "容積移轉方式",
          "土地捐贈 / 送出基地",
          "折繳代金",
          "混合方式",
          "臨路條件 A",
          "接受基地內部條件 B",
          "外部環境改善項目 C",
          "加成係數",
          "預估可移入容積比例",
          "預估可移入容積坪數",
          "折繳代金比例",
          "預估代金金額",
          "是否納入成本",
        ],
      },
    ],
  },
  {
    id: "ownership",
    title: "土地清冊 / 建物清冊",
    eyebrow: "LIST",
    description: "第一階段先做前端表格骨架，未來再接 Excel 匯入與地主整合狀態。",
    sections: [
      {
        title: "土地清冊",
        tableColumns: ["地主姓名", "地號", "持分比例", "持分面積", "聯絡方式", "同意狀態", "備註"],
      },
      {
        title: "建物清冊",
        tableColumns: ["建號", "所有權人", "建物面積", "樓層", "用途", "屋齡", "是否出租", "是否抵押", "同意狀態", "備註"],
      },
    ],
  },
  {
    id: "efficiency",
    title: "坪效明細計算",
    eyebrow: "AREA",
    description: "快速模式只作前期參考；正式成本、損益、融資報告以明細坪效計算結果為主要依據。",
    sections: [
      {
        title: "快速坪效估算",
        formula: "土地坪效 = 基準容積率 x（1 + 獎勵值合計）x 銷售係數；預估可售坪數 = 土地坪效 x 基地面積",
        fields: [
          "基準容積率",
          "都更獎勵",
          "危老獎勵",
          "容積移轉",
          "其他獎勵",
          "獎勵值合計",
          "銷售係數：1.68 / 1.65 / 1.60 / 1.58 / 自訂",
          "土地坪效",
          "預估可售坪數",
        ],
      },
      {
        title: "明細坪效計算",
        fields: [
          "基準容積樓地板面積",
          "獎勵容積面積",
          "容積移轉面積",
          "免計容積面積",
          "地上樓地板面積",
          "地下樓地板面積",
          "總樓地板面積",
          "車位數",
          "公設比",
          "可售坪數",
          "每坪土地產生可售坪",
        ],
      },
    ],
  },
  {
    id: "costs",
    title: "成本與共同負擔",
    eyebrow: "COST",
    description: "以都市更新共同負擔項目作為基準，先區分現金流支出、最終成本與可返還保證金。",
    sections: [
      {
        title: "成本大類",
        fields: [
          "工程類成本",
          "規劃設計與專業服務費",
          "權利變換與行政費用",
          "容積取得成本",
          "標章、獎勵與保證金成本",
          "融資與財務費用",
          "銷售與管理費用",
          "預備金與其他費用",
        ],
      },
      {
        title: "標章、獎勵與保證金成本",
        fields: [
          "綠建築",
          "智慧建築",
          "耐震設計",
          "無障礙設計",
          "低碳建築",
          "建築能效",
          "保證金",
          "預計返還金額",
          "是否可返還",
          "預計返還時間",
          "若未取得標章是否轉列成本",
        ],
      },
      {
        title: "成本性質標籤",
        options: ["現金流支出", "最終成本", "可返還保證金"],
      },
    ],
  },
  {
    id: "allocation",
    title: "實施方式與權利分配",
    eyebrow: "RIGHTS",
    description: "依開發路徑帶出不同分配模式，先建立輸入欄位與摘要卡。",
    sections: [
      {
        title: "購地自建",
        fields: ["土地取得總價", "土地取得單價", "土地融資成數", "土地貸款金額", "土地利息", "開發方可銷售坪數"],
      },
      {
        title: "一般合建",
        fields: ["每坪土地換建坪", "地主分回坪數", "地主分回車位", "開發方可銷售坪數", "找補金額"],
      },
      {
        title: "危老重建",
        fields: ["每坪土地換建坪", "地主分回坪數", "危老獎勵", "開發方可銷售坪數"],
      },
      {
        title: "都市更新 / 協議合建",
        fields: ["坪換坪", "比例分配", "自訂分配條件"],
      },
      {
        title: "都市更新 / 權利變換併送",
        fields: ["預估本人更新後分配之權利價值比率", "估價師暫估值", "正式估價版本備註"],
      },
      {
        title: "都市更新 / 權利變換分送",
        fields: ["預估權利變換分配比率", "預估共同負擔比例", "未來權利變換計畫正式值備註"],
      },
      {
        title: "自主更新",
        fields: ["地主自辦主體", "是否成立更新會", "專業團隊服務費", "每戶自負額", "地主更新後分配面積", "融資需求", "是否需出售部分戶別回收成本"],
      },
    ],
  },
  {
    id: "sales",
    title: "銷售價格情境",
    eyebrow: "SALES",
    description: "以 25 萬 / 坪為預設起始單價，級距 1 萬 / 坪，結束單價由使用者設定。",
    sections: [
      {
        title: "價格區間表",
        tableColumns: ["銷售單價", "開發方可銷售坪數", "總銷售收入", "總開發成本", "預估利潤", "利潤率", "損益平衡狀態"],
      },
    ],
  },
  {
    id: "cashflow",
    title: "現金流與資金需求",
    eyebrow: "CASH",
    description: "依開發時程建立支出、收入、融資撥款與資金缺口摘要。",
    sections: [
      {
        title: "階段骨架",
        tableColumns: ["階段", "起始時間", "結束時間", "支出金額", "收入金額", "融資撥款", "自有資金投入", "累積現金流", "資金缺口"],
        rows: ["前期評估", "地主整合", "規劃設計", "都更 / 危老申請", "審議階段", "建照階段", "拆遷安置", "開工", "結構工程", "裝修工程", "使照取得", "銷售回收", "交屋結算"],
      },
    ],
  },
  {
    id: "bank-report",
    title: "銀行融資報告",
    eyebrow: "BANK",
    description: "第一階段先建立報告章節骨架，後續再串接資料與 PDF 輸出。",
    sections: [
      {
        title: "報告章節",
        fields: [
          "案件摘要",
          "基地條件",
          "開發路徑",
          "土地與建物權屬概況",
          "容積來源與獎勵",
          "坪效試算摘要",
          "成本估算",
          "分配條件",
          "銷售情境",
          "損益平衡",
          "現金流與資金需求",
          "融資需求",
          "還款來源",
          "風險說明",
          "結論建議",
        ],
      },
    ],
  },
  {
    id: "parameters",
    title: "參數設定",
    eyebrow: "PARAM",
    description: "先建立全系統預設參數與案件個別參數，後續再加入權限與版本控管。",
    sections: [
      {
        title: "案件個別參數",
        access: "user",
        fields: [
          "案件公設比",
          "案件銷售係數",
          "案件營建成本單價",
          "案件設計費率",
          "案件管理費率",
          "案件銷售費率",
          "案件利率",
          "案件不可預見費率",
          "案件銷售價格起始單價",
          "案件銷售價格結束單價",
          "案件銷售價格級距",
        ],
      },
      {
        title: "全系統預設參數",
        access: "admin",
        fields: [
          "預設公設比",
          "預設銷售係數",
          "預設營建成本單價",
          "預設設計費率",
          "預設管理費率",
          "預設銷售費率",
          "預設利率",
          "預設不可預見費率",
          "銷售價格起始單價",
          "銷售價格結束單價",
          "銷售價格級距",
        ],
      },
      {
        title: "參數層級",
        options: ["案件個別參數：一般使用者可看可調整", "全系統預設參數：僅三策管理員可看可調整"],
      },
    ],
  },
  {
    id: "license-management",
    title: "授權與帳號管理",
    eyebrow: "AUTH",
    shortTitle: "授權管理",
    description:
      "建立三策管理端核發帳號、授權期限、模組權限、報告匯出與設備綁定管控骨架。第一版授權限制規則為一個帳號最多只能綁定 1 台設備。",
    type: "license",
    loginPrinciples: [
      "本系統不開放公開註冊",
      "使用者帳號由三策管理端建立",
      "使用者以 email + 三策核發密碼登入",
      "密碼可由三策管理端重設",
      "預留第一次登入修改密碼機制",
      "預留管理員停用帳號機制",
      "預留授權到期後禁止使用機制",
      "第一版設備限制為一個帳號最多綁定 1 台設備",
    ],
    impactAreas: [
      "是否可登入開發評估系統",
      "是否可建立案件",
      "是否可使用特定模組",
      "是否可匯出報告",
      "是否可使用承接評估",
      "是否可使用銀行融資報告",
      "是否允許該設備登入",
      "是否需要管理員解除設備綁定",
    ],
    accountFields: ["使用者 email", "三策核發密碼", "第一次登入修改密碼", "管理員重設密碼", "帳號停用狀態", "授權到期狀態"],
    licenseFields: [
      "使用者 email",
      "公司名稱",
      "聯絡人",
      "聯絡電話",
      "授權狀態",
      "授權起日",
      "授權迄日",
      "授權方案",
      "可建立案件數",
      "已建立案件數",
      "可使用模組",
      "可匯出報告次數",
      "已匯出報告次數",
      "是否可使用銀行融資報告",
      "是否可使用承接評估",
      "備註",
    ],
    deviceControlFields: [
      "allowedDeviceCount：預設值為 1",
      "boundDeviceCount",
      "boundDeviceId",
      "boundDeviceName",
      "deviceBoundAt",
      "lastLoginAt",
      "lastLoginIp",
      "lastLoginUserAgent",
      "currentSessionId",
      "currentSessionStartedAt",
      "是否允許多裝置登入：第一版預設否",
      "是否強制單一 session：第一版預設是",
      "requireDeviceReset",
      "異常登入提醒",
      "設備綁定備註",
    ],
    ipControlFields: [
      "是否啟用 IP 限制",
      "允許 IP 白名單",
      "最近登入 IP 記錄",
      "最近登入地區",
      "非白名單登入處理方式",
      "是否通知管理員",
      "IP 限制備註",
    ],
    sections: [
      {
        title: "授權管理欄位",
        fields: [
          "使用者 email",
          "公司名稱",
          "聯絡人",
          "聯絡電話",
          "授權狀態",
          "授權起日",
          "授權迄日",
          "授權方案",
          "可建立案件數",
          "已建立案件數",
          "可使用模組",
          "可匯出報告次數",
          "已匯出報告次數",
          "是否可使用銀行融資報告",
          "是否可使用承接評估",
          "備註",
        ],
        options: ["啟用", "停用", "到期"],
      },
      {
        title: "設備與 session 管控",
        fields: [
          "allowedDeviceCount：預設值為 1",
          "boundDeviceCount",
          "boundDeviceId",
          "boundDeviceName",
          "deviceBoundAt",
          "lastLoginAt",
          "lastLoginIp",
          "lastLoginUserAgent",
          "currentSessionId",
          "currentSessionStartedAt",
          "是否允許多裝置登入：第一版預設否",
          "是否強制單一 session：第一版預設是",
          "requireDeviceReset",
          "異常登入提醒",
          "設備綁定備註",
        ],
      },
      {
        title: "IP 管控欄位",
        formula: "IP 限制第一版作為輔助，不作為主要管控方式；主要管控仍是帳號授權 + 單一設備綁定。",
        fields: [
          "是否啟用 IP 限制",
          "允許 IP 白名單",
          "最近登入 IP 記錄",
          "最近登入地區",
          "非白名單登入處理方式",
          "是否通知管理員",
          "IP 限制備註",
        ],
      },
    ],
    deviceRules: [
      "第一次成功登入時，系統綁定該設備",
      "後續登入必須符合已綁定設備",
      "一個帳號最多只能綁定 1 台設備",
      "第二台設備不能直接登入",
      "第二台設備登入時，應顯示：此帳號已綁定其他設備，請聯絡三策管理員解除原設備綁定",
      "管理端解除綁定後，使用者才能在新設備登入",
      "管理端可查看最近登入時間、IP、瀏覽器與裝置資訊",
    ],
    secondDeviceWarning: {
      title: "此帳號已綁定其他設備",
      description:
        "為保護授權使用權限，一個帳號僅能綁定一台設備。若您需要更換設備，請聯絡三策管理員解除原設備綁定。",
      actions: ["聯絡管理員", "返回登入", "查看授權說明"],
    },
    adminActions: [
      "建立帳號",
      "停用帳號",
      "啟用帳號",
      "重設密碼",
      "延長授權期限",
      "調整授權方案",
      "調整可建立案件數",
      "調整可使用模組",
      "查看登入紀錄",
      "查看綁定設備",
      "解除設備綁定",
      "強制登出",
      "查看異常登入",
      "匯出授權清冊",
    ],
    licensePlans: [
      {
        title: "基礎版",
        items: ["新案前期評估", "基地基本資料", "開發路徑選擇", "快速坪效估算"],
      },
      {
        title: "專業版",
        items: ["成本與共同負擔", "實施方式與權利分配", "銷售價格情境", "現金流與資金需求"],
      },
      {
        title: "銀行報告版",
        items: ["銀行融資報告", "報告輸出", "融資需求摘要"],
      },
      {
        title: "顧問版",
        items: ["多案件管理", "承接評估", "既有條件反推", "多模組完整使用"],
      },
    ],
  },
  {
    id: "security-protection",
    title: "系統安全防護",
    eyebrow: "SAFE",
    shortTitle: "安全防護",
    description:
      "建立開發評估系統未來正式上線前需要的安全防護規劃骨架，涵蓋登入授權、單一設備、API 權限、資料隔離、稽核紀錄、異常偵測、備份復原與部署保護。",
    type: "security",
    riskLevels: ["已規劃", "待後端實作", "待資料庫規則", "高優先"],
    overviewCards: [
      { title: "授權帳號控管", status: "已規劃" },
      { title: "單一設備綁定", status: "高優先" },
      { title: "Session 管控", status: "待後端實作" },
      { title: "API 權限驗證", status: "待後端實作" },
      { title: "客戶資料隔離", status: "待資料庫規則" },
      { title: "稽核紀錄", status: "待後端實作" },
      { title: "異常登入偵測", status: "高優先" },
      { title: "備份與復原", status: "已規劃" },
    ],
    sections: [
      {
        title: "登入與授權防護",
        items: [
          "不開放公開註冊",
          "帳號由三策管理端建立",
          "email + 三策核發密碼登入",
          "密碼由管理端重設",
          "授權到期禁止使用",
          "帳號停用立即禁止登入",
          "可使用模組依授權方案限制",
          "報告匯出依授權方案限制",
          "承接評估依授權方案限制",
        ],
        risk: "高優先",
      },
      {
        title: "單一設備綁定",
        items: [
          "一個帳號最多綁定 1 台設備",
          "allowedDeviceCount = 1",
          "第一次登入綁定設備",
          "第二台設備登入時阻擋",
          "管理端可解除設備綁定",
          "記錄 deviceId、deviceName、userAgent、IP、綁定時間、最近登入時間",
        ],
        risk: "高優先",
      },
      {
        title: "Session 與登入紀錄",
        fields: [
          "sessionId",
          "userId",
          "deviceId",
          "loginAt",
          "logoutAt",
          "expiresAt",
          "lastActiveAt",
          "ipAddress",
          "userAgent",
          "loginResult",
          "failureReason",
          "forceLogoutByAdmin",
          "suspiciousLoginFlag",
        ],
        items: [
          "單一有效 session",
          "長時間閒置自動登出",
          "高風險事件要求重新登入",
          "管理員可強制登出",
          "登入失敗次數記錄",
          "暴力登入防護預留",
        ],
        risk: "待後端實作",
      },
      {
        title: "API 與後端存取防護",
        items: [
          "所有 API 必須驗證登入 session",
          "所有 API 必須檢查授權狀態",
          "所有 API 必須檢查設備綁定狀態",
          "所有案件資料 API 必須檢查 companyId / userId",
          "不可信任前端傳來的權限資料",
          "不讓前端直接決定是否可存取模組",
          "匯出報告 API 必須二次確認授權",
          "管理端 API 必須檢查 admin role",
          "所有敏感操作要寫入 audit log",
        ],
        risk: "待後端實作",
      },
      {
        title: "客戶資料隔離",
        fields: ["companyId", "accountId", "caseId", "createdBy", "ownerUserId", "allowedUserIds", "role", "dataAccessScope"],
        items: [
          "A 公司不能看到 B 公司的案件",
          "使用者只能存取自己公司或被授權的案件",
          "管理員操作需留紀錄",
          "案件、參數、報告、匯出檔都要綁定 companyId / accountId",
        ],
        risk: "待資料庫規則",
      },
      {
        title: "輸入驗證與內容安全",
        items: [
          "所有文字輸入需限制長度",
          "金額、坪數、比例、日期需格式驗證",
          "不允許 HTML script 注入",
          "報告備註欄位需過濾危險內容",
          "檔案上傳需限制格式與大小",
          "Excel 匯入需檢查欄位與公式風險",
          "前端顯示內容需避免 XSS",
          "後端也必須重新驗證，不只靠前端",
        ],
        risk: "高優先",
      },
      {
        title: "報告匯出與檔案下載防護",
        items: [
          "報告匯出需檢查授權方案",
          "報告匯出需檢查案件權限",
          "下載連結需有時效",
          "下載連結不可永久公開",
          "報告檔案需綁定 accountId / caseId",
          "匯出報告需寫入 audit log",
          "超出匯出次數要阻擋",
          "重要報告可加浮水印或使用者資訊",
        ],
        risk: "高優先",
      },
      {
        title: "稽核紀錄與操作日誌",
        fields: [
          "auditId",
          "accountId",
          "userId",
          "companyId",
          "actionType",
          "targetType",
          "targetId",
          "beforeValue",
          "afterValue",
          "ipAddress",
          "userAgent",
          "createdAt",
          "riskLevel",
        ],
        items: [
          "登入",
          "登出",
          "登入失敗",
          "第二台設備登入被阻擋",
          "解除設備綁定",
          "建立案件",
          "修改基地資料",
          "修改成本參數",
          "修改分配條件",
          "匯出報告",
          "修改授權方案",
          "停用帳號",
          "重設密碼",
          "管理員強制登出",
        ],
        risk: "待後端實作",
      },
      {
        title: "異常行為偵測與通知",
        items: [
          "短時間多次登入失敗",
          "不同 IP 頻繁切換",
          "不同裝置嘗試登入",
          "非白名單 IP 登入",
          "大量匯出報告",
          "短時間大量建立案件",
          "權限不足仍嘗試存取模組",
          "非管理員嘗試進入管理功能",
          "管理端警示",
          "email 通知",
          "系統內通知",
          "登入阻擋提示",
        ],
        risk: "高優先",
      },
      {
        title: "備份與復原",
        items: [
          "帳號授權資料備份",
          "案件資料備份",
          "參數設定備份",
          "報告輸出紀錄備份",
          "audit log 備份",
          "定期備份頻率",
          "還原流程",
          "誤刪復原",
          "災難復原備註",
        ],
        risk: "已規劃",
      },
      {
        title: "環境變數與金鑰管理",
        items: [
          "API key 不得放在前端",
          "管理員密鑰不得放在前端",
          "資料庫 service key 不得放在前端",
          "所有敏感金鑰放在 Vercel Environment Variables",
          "不在 console.log 顯示 token",
          "不把 .env commit 到 GitHub",
          "production / preview / development 環境分開",
          "密鑰定期輪替",
        ],
        risk: "高優先",
      },
      {
        title: "部署與 Vercel 保護",
        items: [
          "Production branch 僅 main",
          "不使用 force push",
          "重要功能先在本機驗證",
          "build 通過才部署",
          "管理端 route 未授權不可進入",
          "未來 API route 需檢查 session",
          "Preview deployment 不可暴露正式資料",
          "Vercel env 權限控管",
          "部署後檢查首頁與系統入口",
        ],
        risk: "已規劃",
      },
      {
        title: "未來資料庫安全規則",
        fields: ["users / accounts", "companies", "licenses", "devices", "sessions", "cases", "case_parameters", "reports", "audit_logs"],
        items: [
          "每筆 case 綁定 companyId",
          "每筆 report 綁定 companyId / caseId",
          "使用者只能讀寫授權範圍內資料",
          "管理員權限獨立控管",
          "裝置綁定需在登入時檢查",
          "session 需有到期時間",
          "刪除重要資料需軟刪除或留紀錄",
          "audit_logs 不允許一般使用者修改",
        ],
        risk: "待資料庫規則",
      },
    ],
    plannedControls: [
      "授權狀態檢查",
      "單一設備綁定",
      "單一有效 session",
      "API session 驗證",
      "companyId / userId 資料隔離",
      "報告匯出授權二次確認",
      "audit log 全程記錄",
      "異常登入通知",
    ],
    backendRequirements: [
      "正式登入 session 驗證",
      "授權方案與模組權限檢查",
      ...roleVisibilityRules.backendRequirements,
      "設備綁定驗證",
      "API route 權限 middleware",
      "報告下載短效連結",
      "管理端角色檢查",
      "暴力登入防護與 rate limit",
      "敏感操作 audit log",
    ],
    databaseRulePlaceholders: [
      "users / accounts",
      "companies",
      "licenses",
      "devices",
      "sessions",
      "cases",
      "case_parameters",
      "reports",
      "audit_logs",
    ],
    auditLogFields: [
      "auditId",
      "accountId",
      "userId",
      "companyId",
      "actionType",
      "targetType",
      "targetId",
      "beforeValue",
      "afterValue",
      "ipAddress",
      "userAgent",
      "createdAt",
      "riskLevel",
    ],
  },
];
