export const ROSTER_STANDARD_SCHEMA_VERSION = "urban-renewal-roster-2026-05-15";

export const ROSTER_STANDARD_SHEET_NAMES = {
  land: "土地權屬清冊",
  building: "合法建物權屬清冊",
};

export const ROSTER_STANDARD_BLOCKS = {
  sequence: "序號",
  identification: "標示部",
  ownership: "所有權部",
  otherRights: "他項權利部",
  notes: "備註 / 謄本地址",
  buildingSupplement: "建物補充資訊",
  validation: "系統檢核",
};

export const LAND_STANDARD_FIELDS = [
  { id: "landSequence", block: "sequence", label: "序號", source: "原始清冊欄位", required: false },
  { id: "sectionName", block: "identification", label: "地段", source: "原始清冊欄位", required: true },
  { id: "landNumber", block: "identification", label: "地號", source: "原始清冊欄位", required: true },
  { id: "landAreaSqm", block: "identification", label: "面積(㎡)", source: "原始清冊欄位", required: true },
  { id: "ownerRegistrationOrder", block: "ownership", label: "登記次序", source: "原始清冊欄位", required: false },
  { id: "ownerName", block: "ownership", label: "所有權人(管理人)", source: "原始清冊欄位", required: true },
  { id: "ownerIdNumber", block: "ownership", label: "身分證字號", source: "原始清冊欄位", required: false },
  { id: "shareNumerator", block: "ownership", label: "權利範圍分子", source: "原始清冊欄位", required: true },
  { id: "shareSlash", block: "ownership", label: "權利範圍斜線欄", source: "原始清冊欄位", required: false },
  { id: "shareDenominator", block: "ownership", label: "權利範圍分母", source: "原始清冊欄位", required: true },
  { id: "originalShareAreaSqm", block: "ownership", label: "土地持分面積(㎡)", source: "原始清冊欄位", required: false },
  { id: "otherRightRegistrationOrder", block: "otherRights", label: "他項權利登記次序", source: "原始清冊欄位", required: false },
  { id: "otherRightType", block: "otherRights", label: "權利種類", source: "原始清冊欄位", required: false },
  { id: "otherRightHolder", block: "otherRights", label: "他項權利人", source: "原始清冊欄位", required: false },
  { id: "debtor", block: "otherRights", label: "債務人", source: "原始清冊欄位", required: false },
  { id: "debtorAndDebtRatio", block: "otherRights", label: "債務人及債務額比例", source: "原始清冊欄位", required: false },
  { id: "obligor", block: "otherRights", label: "設定義務人", source: "原始清冊欄位", required: false },
  { id: "securedAmount", block: "otherRights", label: "金額", source: "原始清冊欄位", required: false },
  { id: "securedAmountRaw", block: "otherRights", label: "金額原文", source: "原始謄本欄位", required: false },
  { id: "securedAmountNumber", block: "otherRights", label: "金額數值", source: "系統解析欄位", required: false },
  { id: "securedClaimScope", block: "otherRights", label: "擔保債權種類及範圍", source: "原始謄本欄位", required: false },
  { id: "otherRightNote", block: "otherRights", label: "他項權利備註", source: "原始謄本欄位", required: false },
  { id: "note", block: "notes", label: "備註", source: "原始清冊欄位", required: false },
  { id: "transcriptAddress", block: "notes", label: "謄本地址", source: "原始清冊欄位", required: false },
  { id: "calculatedShareAreaSqm", block: "validation", label: "系統驗算持分面積(㎡)", source: "系統重算欄位", required: false },
  { id: "shareAreaDifferenceSqm", block: "validation", label: "持分面積差異(㎡)", source: "檢核欄位", required: false },
  { id: "shareAreaPing", block: "validation", label: "持分面積坪", source: "系統重算欄位", required: false },
  { id: "validationStatus", block: "validation", label: "檢核狀態", source: "檢核欄位", required: false },
  { id: "validationMessages", block: "validation", label: "檢核訊息", source: "檢核欄位", required: false },
];

export const BUILDING_STANDARD_FIELDS = [
  { id: "buildingSequence", block: "sequence", label: "編號", source: "原始清冊欄位", required: false },
  { id: "buildingNumber", block: "identification", label: "建號", source: "原始清冊欄位", required: true },
  { id: "buildingDoorplate", block: "identification", label: "建物門牌號碼", source: "原始清冊欄位", required: true },
  { id: "buildingTotalAreaSqm", block: "identification", label: "面積(m2)-合計", source: "原始清冊欄位", required: true },
  { id: "mainBuildingAreaSqm", block: "identification", label: "面積(m2)-主建物", source: "原始清冊欄位", required: false },
  { id: "accessoryBuildingAreaSqm", block: "identification", label: "面積(m2)-附屬建物", source: "原始清冊欄位", required: false },
  { id: "locatedLandNumber", block: "identification", label: "座落地號", source: "原始清冊欄位", required: true },
  { id: "ownerRegistrationOrder", block: "ownership", label: "登記次序", source: "原始清冊欄位", required: false },
  { id: "ownerName", block: "ownership", label: "所有權人(管理人)", source: "原始清冊欄位", required: true },
  { id: "ownerIdNumber", block: "ownership", label: "身分證字號", source: "原始清冊欄位", required: false },
  { id: "shareNumerator", block: "ownership", label: "權利範圍分子", source: "原始清冊欄位", required: true },
  { id: "shareSlash", block: "ownership", label: "權利範圍斜線欄", source: "原始清冊欄位", required: false },
  { id: "shareDenominator", block: "ownership", label: "權利範圍分母", source: "原始清冊欄位", required: true },
  { id: "originalShareAreaSqm", block: "ownership", label: "持分面積(m2)", source: "原始清冊欄位", required: false },
  { id: "otherRightRegistrationOrder", block: "otherRights", label: "他項權利登記次序", source: "原始清冊欄位", required: false },
  { id: "otherRightType", block: "otherRights", label: "權利種類", source: "原始清冊欄位", required: false },
  { id: "otherRightHolder", block: "otherRights", label: "他項權利人", source: "原始清冊欄位", required: false },
  { id: "debtor", block: "otherRights", label: "債務人", source: "原始清冊欄位", required: false },
  { id: "debtorAndDebtRatio", block: "otherRights", label: "債務人及債務額比例", source: "原始清冊欄位", required: false },
  { id: "obligor", block: "otherRights", label: "設定義務人", source: "原始清冊欄位", required: false },
  { id: "note", block: "notes", label: "備註", source: "原始清冊欄位", required: false },
  { id: "transcriptAddress", block: "notes", label: "謄本地址", source: "原始清冊欄位", required: false },
  { id: "floorLevel", block: "buildingSupplement", label: "層次", source: "原始清冊欄位", required: false },
  { id: "totalFloors", block: "buildingSupplement", label: "總層數", source: "原始清冊欄位", required: false },
  { id: "structureType", block: "buildingSupplement", label: "構造", source: "原始清冊欄位", required: false },
  { id: "completionDate", block: "buildingSupplement", label: "建築完成日期", source: "原始清冊欄位", required: false },
  { id: "calculatedShareAreaSqm", block: "validation", label: "系統驗算持分面積(m2)", source: "系統重算欄位", required: false },
  { id: "shareAreaDifferenceSqm", block: "validation", label: "持分面積差異(m2)", source: "檢核欄位", required: false },
  { id: "shareAreaPing", block: "validation", label: "持分面積坪", source: "系統重算欄位", required: false },
  { id: "validationStatus", block: "validation", label: "檢核狀態", source: "檢核欄位", required: false },
  { id: "validationMessages", block: "validation", label: "檢核訊息", source: "檢核欄位", required: false },
];

export const LAND_PREVIEW_COLUMNS = [
  ["landSequence", "序號"],
  ["sectionName", "地段"],
  ["landNumber", "地號"],
  ["landAreaSqm", "土地面積(㎡)"],
  ["ownerRegistrationOrder", "登記次序"],
  ["ownerName", "所有權人"],
  ["ownerIdNumber", "身分證字號"],
  ["shareDisplay", "權利範圍"],
  ["originalShareAreaSqm", "土地持分面積(㎡)"],
  ["calculatedShareAreaSqm", "系統驗算持分面積(㎡)"],
  ["shareAreaDifferenceSqm", "持分面積差異"],
  ["otherRightType", "他項權利種類"],
  ["otherRightHolder", "他項權利人"],
  ["debtor", "債務人"],
  ["obligor", "設定義務人"],
  ["securedAmount", "金額"],
  ["note", "備註"],
  ["transcriptAddress", "謄本地址"],
  ["validationStatus", "檢核狀態"],
].map(([key, label]) => ({ key, label }));

export const BUILDING_PREVIEW_COLUMNS = [
  ["buildingSequence", "編號"],
  ["buildingNumber", "建號"],
  ["buildingDoorplate", "建物門牌"],
  ["buildingTotalAreaSqm", "建物總面積(m2)"],
  ["mainBuildingAreaSqm", "主建物(m2)"],
  ["accessoryBuildingAreaSqm", "附屬建物(m2)"],
  ["locatedLandNumber", "座落地號"],
  ["ownerRegistrationOrder", "登記次序"],
  ["ownerName", "所有權人"],
  ["ownerIdNumber", "身分證字號"],
  ["shareDisplay", "權利範圍"],
  ["originalShareAreaSqm", "持分面積(m2)"],
  ["calculatedShareAreaSqm", "系統驗算持分面積(m2)"],
  ["shareAreaDifferenceSqm", "持分面積差異"],
  ["otherRightType", "他項權利種類"],
  ["otherRightHolder", "他項權利人"],
  ["debtor", "債務人"],
  ["obligor", "設定義務人"],
  ["note", "備註"],
  ["transcriptAddress", "謄本地址"],
  ["floorLevel", "層次"],
  ["totalFloors", "總層數"],
  ["structureType", "構造"],
  ["completionDate", "建築完成日期"],
  ["validationStatus", "檢核狀態"],
].map(([key, label]) => ({ key, label }));

export const LAND_EXPORT_HEADERS = [
  "序號",
  "地段",
  "地號",
  "面積(㎡)",
  "登記次序",
  "所有權人(管理人)",
  "身分證字號",
  "權利範圍分子",
  "/",
  "權利範圍分母",
  "原始土地持分面積(㎡)",
  "系統驗算持分面積(㎡)",
  "持分面積差異(㎡)",
  "持分面積坪",
  "他項權利登記次序",
  "權利種類",
  "他項權利人",
  "債務人",
  "債務人及債務額比例",
  "設定義務人",
  "金額",
  "備註",
  "謄本地址",
  "檢核狀態",
  "檢核訊息",
];

export const BUILDING_EXPORT_HEADERS = [
  "編號",
  "建號",
  "建物門牌號碼",
  "面積(m2)-合計",
  "面積(m2)-主建物",
  "面積(m2)-附屬建物",
  "座落地號",
  "登記次序",
  "所有權人(管理人)",
  "身分證字號",
  "權利範圍分子",
  "/",
  "權利範圍分母",
  "原始持分面積(m2)",
  "系統驗算持分面積(m2)",
  "持分面積差異(m2)",
  "持分面積坪",
  "他項權利登記次序",
  "權利種類",
  "他項權利人",
  "債務人",
  "債務人及債務額比例",
  "設定義務人",
  "備註",
  "謄本地址",
  "層次",
  "總層數",
  "構造",
  "建築完成日期",
  "檢核狀態",
  "檢核訊息",
];

export const LAND_TEMPLATE_HEADERS = [
  "序號",
  "地段",
  "地號",
  "面積(㎡)",
  "登記次序",
  "所有權人(管理人)",
  "身分證字號",
  "權利範圍分子",
  "/",
  "權利範圍分母",
  "土地持分面積(㎡)",
  "他項權利登記次序",
  "權利種類",
  "他項權利人",
  "債務人",
  "債務人及債務額比例",
  "設定義務人",
  "金額",
  "備註",
  "謄本地址",
];

export const BUILDING_TEMPLATE_HEADERS = [
  "編號",
  "建號",
  "建物門牌號碼",
  "面積(m2)-合計",
  "面積(m2)-主建物",
  "面積(m2)-附屬建物",
  "座落地號",
  "登記次序",
  "所有權人(管理人)",
  "身分證字號",
  "權利範圍分子",
  "/",
  "權利範圍分母",
  "持分面積(m2)",
  "他項權利登記次序",
  "權利種類",
  "他項權利人",
  "債務人",
  "債務人及債務額比例",
  "設定義務人",
  "備註",
  "謄本地址",
  "層次",
  "總層數",
  "構造",
  "建築完成日期",
];

export function getRosterStandardDictionaryRows() {
  return [
    ["schemaVersion", ROSTER_STANDARD_SCHEMA_VERSION, "系統版本 / schema version"],
    ["土地權屬清冊", ROSTER_STANDARD_SHEET_NAMES.land, "以都市更新權屬清冊實務欄位為基準"],
    ["合法建物權屬清冊", ROSTER_STANDARD_SHEET_NAMES.building, "以都市更新合法建物權屬清冊實務欄位為基準"],
    ...LAND_STANDARD_FIELDS.map((field) => [`土地.${field.id}`, field.label, `${ROSTER_STANDARD_BLOCKS[field.block]} / ${field.source}`]),
    ...BUILDING_STANDARD_FIELDS.map((field) => [`建物.${field.id}`, field.label, `${ROSTER_STANDARD_BLOCKS[field.block]} / ${field.source}`]),
  ];
}
